services:
    backup:
        image: jareware/docker-volume-backup
        env_file: ./.env
        volumes:
            - /var/lib/docker/volumes:/backup//var/lib/docker/volumes:ro # mount all volumes to backup
            - /home/nour/testNourFrontend/Frontend/hackathon-app:/backup/home/nour/testNourFrontend/Frontend/hackathon-app:ro
            - /monitoring/Monitoring/ELK/elasticsearch/data:/backup/monitoring/Monitoring/ELK/elasticsearch/data:ro
        restart: always
