version: "3.8"

services:
    portainer:
        image: portainer/portainer-ee:latest
        container_name: portainer
        ports:
            - "16000:8000"
            - "17443:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        restart: always

volumes:
    portainer_data:
